spring:
  rabbitmq:
    host: 47.74.234.117
    port: 5672
    username: XRom
    password: XRom123
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        prefetch: 5